services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: ./spring-backend
      dockerfile: Dockerfile
    environment:
      MONGODB_ACCESS: mongodb
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata:
